<!-- Morris.js charts -->
<script src="<?php echo base_url() ?>asset/bower_components/raphael/raphael.min.js"></script>
<script src="<?php echo base_url() ?>asset/bower_components/morris.js/morris.min.js"></script>
<!-- jvectormap -->
<script src="<?php echo base_url() ?>asset/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="<?php echo base_url() ?>asset/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="<?php echo base_url() ?>asset/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="<?php echo base_url() ?>asset/dist/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo base_url() ?>asset/dist/js/demo.js"></script>